---
- name: Network Getting Started First Playbook
  gather_facts: true
  hosts: Routers
  tasks:

   - name: Get config from routers
     cisco.ios.ios_facts:
      gather_subset: all
     register: all_subset

   - name: print subset
     debug:
      var: all_subset

   - name: Hardware information
     cisco.ios.ios_facts:
      gather_subset: hardware
     register: hw

   - name: print hw
     debug:
      var: hw

   - name: interfaces information
     cisco.ios.ios_facts:
      gather_subset: interfaces
     register: int

   - name: print int
     debug:
      var: int
