---
- name: Network Getting Started First Playbook
  gather_facts: true
  hosts: Routers
  tasks:
   - name: debug with filters
     debug:
      msg: 
       - "The hostname is {{ansible_net_hostname}}"
       - The ios version is {{ansible_net_version}}
   - debug:
      var: hostvars[inventory_hostname]