---

- name: Dynamic lookup
  hosts: ios
  gather_facts: false

  tasks:
  - name: Eigrp config
    cisco.ios.ios_config:
      src: "{{ eigrp_style }}.j2"
    register: result

  - name: print
    debug:
      msg: "{{ result.commands[0] }}"