---
all:
  children:
    Routers:
      children:
        ios:
          hosts:
            IOS:
              ansible_host: 10.1.1.101
            IOS-1:
              ansible_host: 10.1.1.103
        junos:
          hosts:
            juniper:
              ansible_host: 10.1.1.104
    Switches:
        hosts:
          10.1.1.110:
          10.1.1.111:

          
