---
all:
  children:
    Routers:
      children:
        ios:
          hosts:
            IOS:
              ansible_host: 10.1.1.101
            IOS-1:
              ansible_host: 10.1.1.103
            7200R:
              ansible_host: 10.1.1.110
        junos:
          hosts:
            juniper:
              ansible_host: 10.1.1.104
        arista:
          hosts:
            arista-eos:
              ansible_host: 10.1.1.105
    Switches:
        hosts:
          10.1.1.111:

          
