---

- name: Gather Facts in juniper
  hosts: junos
  gather_facts: true

  tasks:
    - name: juniper config
      junipernetworks.junos.junos_facts:
        gather_subset: config
      register: junos_facts

    - name: print
      debug:
        msg: "{{ junos_facts }}"



