---

- name: Napalm playbook
  hosts: arista
  gather_facts: false

  tasks:
    - name: Get facts using napalm
      napalm.napalm.napalm_get_facts:
        filter: config

      register: result

    - name: print
      debug:
        msg: "{{ result.ansible_facts.napalm_config.running.split('\n') }}"