---

- name: Napalm playbook
  hosts: ios
  gather_facts: false

  tasks:
    - name: Get facts using napalm
      napalm.napalm.napalm_get_facts:
        hostname: "{{ inventory_hostname }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        dev_os: "{{ napalm_platform }}"

      register: result

    - name: print
      debug:
        msg: "{{ result }}"