---

- name: ospf configuration
  hosts: Routers
  gather_facts: false

  tasks:
    - name: ios ospf config
      cisco.ios.ios_ospfv2:
        config:
          processes:
            - process_id: 1
              router_id: "{{ ospf.rid }}"              
              network:
                - address: 10.0.0.0
                  wildcard_bits: 0.0.0.255
                  area: 0
      register: ios_ospf_config
      when: ansible_network_os == 'cisco.ios.ios'

    - name: junos ospf config
      junipernetworks.junos.junos_ospfv2:
        config:
        - router_id: "{{ ospf.rid }}"
        - areas:
          - area_id: 0.0.0.0
            interfaces:
              - name: ge-0/0/2.0
              - name: ge-0/0/3.0
      register: junos_ospf_config
      when: ansible_network_os == 'junipernetworks.junos.junos'

    - name: print ios config
      debug:
        msg: "{{ ios_ospf_config }}"
      when: ansible_network_os == 'cisco.ios.ios'

    - name: print junos config
      debug:
        msg: "{{ junos_ospf_config }}"
      when: ansible_network_os == 'junipernetworks.junos.junos'

      
          